name: vift
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.9.23
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - alembic==1.16.2
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autopage==0.5.2
      - certifi==2025.8.3
      - cfgv==3.4.0
      - charset-normalizer==3.4.3
      - cliff==4.9.1
      - cmaes==0.11.1
      - cmd2==2.6.1
      - colorama==0.4.6
      - colorlog==6.9.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - distlib==0.3.9
      - exceptiongroup==1.3.0
      - filelock==3.18.0
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - greenlet==3.2.3
      - grpcio==1.73.1
      - huggingface-hub==0.34.4
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - identify==2.6.12
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - lightning==2.5.2
      - lightning-utilities==0.14.3
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.5.1
      - natsort==8.4.0
      - networkx==3.2.1
      - nodeenv==1.9.1
      - numpy==2.0.2
      - omegaconf==2.3.0
      - optuna==2.10.1
      - packaging==25.0
      - path==17.1.0
      - pbr==6.1.1
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - pre-commit==4.2.0
      - prettytable==3.16.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyperclip==1.9.0
      - pyreadline3==3.5.4
      - pytest==8.4.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytorch-lightning==2.5.2
      - pyyaml==6.0.2
      - requests==2.32.5
      - rich==14.0.0
      - rootutils==1.0.7
      - scipy==1.13.1
      - six==1.17.0
      - sqlalchemy==2.0.41
      - stevedore==5.4.1
      - sympy==1.14.0
      - tb-nightly==2.20.0a20250626
      - tensorboard-data-server==0.7.2
      - tomli==2.2.1
      - torch==2.7.1+cu126
      - torchaudio==2.7.1+cu126
      - torchmetrics==1.7.3
      - torchvision==0.22.1
      - tqdm==4.67.1
      - typing-extensions==4.14.0
      - urllib3==2.5.0
      - virtualenv==20.31.2
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - yarl==1.20.1
      - zipp==3.23.0
prefix: C:\Users\HP-MY\.conda\envs\vift
